-- CreateEnum
CREATE TYPE "Status" AS ENUM ('DISCOVERY', 'PLOTTING', 'BLOCKING', 'DRAFTING', 'EDITING', 'FINISHED', 'PUBLISHED', 'ONHOLD');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "status" "Status" NOT NULL DEFAULT 'DISCOVERY';
